// LOCALHOST ### GET http://localhost:3000/contacts 
             ### GET http://localhost:3000/contacts/6263aba12cd4e63ffb013688 
             ### GET http://localhost:3000/contacts/6263aba12cd4e63ffb013689
             ### GET http://localhost:3000/contacts/6263aba12cd4e63ffb01368a

// PRODUCTION Deploy ### GET https://cw-cs341.herokuapp.com/contacts 
                     ### GET https://cw-cs341.herokuapp.com/contacts/6263aba12cd4e63ffb013688 
                     ### GET https://cw-cs341.herokuapp.com/contacts/6263aba12cd4e63ffb013689 
                     ### GET https://cw-cs341.herokuapp.com/contacts/6263aba12cd4e63ffb01368a